Traceback (most recent call last):
  File "/home/pi/ruuvi/read_write_v2.py", line 40, in <module>
    db.close()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 505, in __exit__
    self.commit()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 419, in commit
    self._execute_command(COMMAND.COM_QUERY, "COMMIT")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
